/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GdkPixbuf *window1_icon_pixbuf;
  GtkWidget *notebook1;
  GtkWidget *fixed1;
  GtkWidget *frame2;
  GtkWidget *alignment2;
  GtkWidget *fixed5;
  GtkWidget *vdr_start;
  GtkWidget *alignment10;
  GtkWidget *hbox6;
  GtkWidget *image7;
  GtkWidget *label27;
  GtkWidget *vdr_stop;
  GtkWidget *alignment12;
  GtkWidget *hbox8;
  GtkWidget *image9;
  GtkWidget *label29;
  GtkWidget *wpvrscan;
  GtkWidget *videodir;
  GtkWidget *language_automatic;
  GtkWidget *language_manuel;
  GtkWidget *vdr_autostart;
  GtkWidget *vdr_disable_autostart;
  GtkWidget *channelslist;
  GtkWidget *alignment17;
  GtkWidget *hbox12;
  GtkWidget *image14;
  GtkWidget *label34;
  GtkWidget *label13;
  GtkWidget *sidux_eventbox1;
  GtkWidget *image12;
  GtkWidget *vdr_eventbox2;
  GtkWidget *image17;
  GtkWidget *update;
  GtkWidget *alignment15;
  GtkWidget *hbox11;
  GtkWidget *image13;
  GtkWidget *label32;
  GtkWidget *Exit;
  GtkWidget *alignment18;
  GtkWidget *hbox13;
  GtkWidget *image15;
  GtkWidget *label35;
  GtkWidget *frame1;
  GtkWidget *alignment1;
  GtkWidget *fixed4;
  GtkWidget *vdr_sxfe;
  GtkWidget *alignment13;
  GtkWidget *hbox9;
  GtkWidget *image10;
  GtkWidget *label30;
  GtkWidget *vdr_sxfe_disable_autostart;
  GtkWidget *vdr_sxfe_autostart;
  GtkWidget *label8;
  GtkWidget *frame4;
  GtkWidget *alignment5;
  GtkWidget *fixed7;
  GtkWidget *IPEntry;
  GtkWidget *label39;
  GtkWidget *allowclient;
  GtkWidget *network_transport_tcp;
  GtkWidget *udp_network_transport;
  GtkWidget *label22;
  GtkWidget *frame5;
  GtkWidget *alignment16;
  GtkWidget *fixed8;
  GtkWidget *fullscreenoff;
  GtkWidget *vdradmin;
  GtkWidget *alignment19;
  GtkWidget *hbox14;
  GtkWidget *image16;
  GtkWidget *label36;
  GtkWidget *user_manual;
  GtkWidget *fullscreen;
  GtkWidget *label33;
  GtkWidget *label37;
  GtkWidget *label1;
  GtkWidget *fixed9;
  GtkWidget *textview1;
  GtkWidget *button1;
  GtkWidget *alignment20;
  GtkWidget *hbox15;
  GtkWidget *image18;
  GtkWidget *label38;
  GtkWidget *label3;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("VDR-GUI"));
  window1_icon_pixbuf = create_pixbuf ("vdr-gui.png");
  if (window1_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (window1), window1_icon_pixbuf);
      gdk_pixbuf_unref (window1_icon_pixbuf);
    }

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (window1), notebook1);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed1);
  gtk_container_set_border_width (GTK_CONTAINER (fixed1), 11);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_show (frame2);
  gtk_fixed_put (GTK_FIXED (fixed1), frame2, 0, 216);
  gtk_widget_set_size_request (frame2, 247, 200);
  gtk_frame_set_shadow_type (GTK_FRAME (frame2), GTK_SHADOW_IN);

  alignment2 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (frame2), alignment2);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment2), 0, 0, 12, 0);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (alignment2), fixed5);

  vdr_start = gtk_button_new ();
  gtk_widget_show (vdr_start);
  gtk_fixed_put (GTK_FIXED (fixed5), vdr_start, 0, 8);
  gtk_widget_set_size_request (vdr_start, 105, 32);
  gtk_container_set_border_width (GTK_CONTAINER (vdr_start), 1);
  gtk_tooltips_set_tip (tooltips, vdr_start, _("start VDR"), NULL);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (vdr_start), alignment10);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox6);

  image7 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox6), image7, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("VDR-Start"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox6), label27, FALSE, FALSE, 0);

  vdr_stop = gtk_button_new ();
  gtk_widget_show (vdr_stop);
  gtk_fixed_put (GTK_FIXED (fixed5), vdr_stop, 0, 48);
  gtk_widget_set_size_request (vdr_stop, 105, 32);
  gtk_container_set_border_width (GTK_CONTAINER (vdr_stop), 1);
  gtk_tooltips_set_tip (tooltips, vdr_stop, _("stop VDR"), NULL);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (vdr_stop), alignment12);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox8);

  image9 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox8), image9, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("VDR-Stop"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox8), label29, FALSE, FALSE, 0);

  wpvrscan = gtk_button_new_with_mnemonic (_("wpvrscan"));
  gtk_widget_show (wpvrscan);
  gtk_fixed_put (GTK_FIXED (fixed5), wpvrscan, 0, 152);
  gtk_widget_set_size_request (wpvrscan, 105, 24);
  gtk_container_set_border_width (GTK_CONTAINER (wpvrscan), 1);
  gtk_tooltips_set_tip (tooltips, wpvrscan, _("VDR-Channelscan Analog-Tuner Typ PVR"), NULL);

  videodir = gtk_button_new_with_mnemonic (_("Videodir"));
  gtk_widget_show (videodir);
  gtk_fixed_put (GTK_FIXED (fixed5), videodir, 120, 8);
  gtk_widget_set_size_request (videodir, 105, 24);
  gtk_container_set_border_width (GTK_CONTAINER (videodir), 1);
  gtk_tooltips_set_tip (tooltips, videodir, _("Change your Video Directory (default: /var/lib/video.00)"), NULL);

  language_automatic = gtk_button_new_with_mnemonic (_("Language auto"));
  gtk_widget_show (language_automatic);
  gtk_fixed_put (GTK_FIXED (fixed5), language_automatic, 120, 48);
  gtk_widget_set_size_request (language_automatic, 105, 24);
  gtk_tooltips_set_tip (tooltips, language_automatic, _("Set VDR-language automatically"), NULL);

  language_manuel = gtk_button_new_with_mnemonic (_("Language manuel"));
  gtk_widget_show (language_manuel);
  gtk_fixed_put (GTK_FIXED (fixed5), language_manuel, 120, 80);
  gtk_widget_set_size_request (language_manuel, 105, 24);
  gtk_tooltips_set_tip (tooltips, language_manuel, _("Manually define VDR-language in VDR-OSD-Menu"), NULL);

  vdr_autostart = gtk_button_new_with_mnemonic (_("VDR Autostart"));
  gtk_widget_show (vdr_autostart);
  gtk_fixed_put (GTK_FIXED (fixed5), vdr_autostart, 120, 120);
  gtk_widget_set_size_request (vdr_autostart, 104, 24);
  gtk_container_set_border_width (GTK_CONTAINER (vdr_autostart), 1);
  gtk_tooltips_set_tip (tooltips, vdr_autostart, _("run vdr at systemstart"), NULL);

  vdr_disable_autostart = gtk_button_new_with_mnemonic (_("Disable Autostart"));
  gtk_widget_show (vdr_disable_autostart);
  gtk_fixed_put (GTK_FIXED (fixed5), vdr_disable_autostart, 120, 152);
  gtk_widget_set_size_request (vdr_disable_autostart, 104, 24);
  gtk_container_set_border_width (GTK_CONTAINER (vdr_disable_autostart), 1);
  gtk_tooltips_set_tip (tooltips, vdr_disable_autostart, _("disable vdr systemstart"), NULL);

  channelslist = gtk_button_new ();
  gtk_widget_show (channelslist);
  gtk_fixed_put (GTK_FIXED (fixed5), channelslist, 0, 112);
  gtk_widget_set_size_request (channelslist, 105, 32);
  gtk_container_set_border_width (GTK_CONTAINER (channelslist), 1);
  gtk_tooltips_set_tip (tooltips, channelslist, _("Change VDR Channelslist. If you don't find your's, then use channelscan from OSD in your TV Picture, or search the Internet for w_scan. Save the channels.conf to /var/lib/vdr/channels.conf. SET USER AND GROUP  TO vdr (chown vdr:vdr channels.conf)"), NULL);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (channelslist), alignment17);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox12);

  image14 = gtk_image_new_from_stock ("gtk-justify-left", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox12), image14, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("Channellist"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox12), label34, FALSE, FALSE, 0);

  label13 = gtk_label_new (_("<b>VDR</b>"));
  gtk_widget_show (label13);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), label13);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);
  gtk_label_set_width_chars (GTK_LABEL (label13), 0);

  sidux_eventbox1 = gtk_event_box_new ();
  gtk_widget_show (sidux_eventbox1);
  gtk_fixed_put (GTK_FIXED (fixed1), sidux_eventbox1, 32, 0);
  gtk_widget_set_size_request (sidux_eventbox1, 82, 32);
  gtk_tooltips_set_tip (tooltips, sidux_eventbox1, _("http://www.sidux.com"), NULL);

  image12 = create_pixmap (window1, "sidux-vdr.png");
  gtk_widget_show (image12);
  gtk_container_add (GTK_CONTAINER (sidux_eventbox1), image12);
  gtk_widget_set_size_request (image12, 82, 32);

  vdr_eventbox2 = gtk_event_box_new ();
  gtk_widget_show (vdr_eventbox2);
  gtk_fixed_put (GTK_FIXED (fixed1), vdr_eventbox2, 368, 0);
  gtk_widget_set_size_request (vdr_eventbox2, 75, 35);
  gtk_tooltips_set_tip (tooltips, vdr_eventbox2, _("http://www.linuxtv.org/vdrwiki"), NULL);

  image17 = create_pixmap (window1, "vdr-gui.png");
  gtk_widget_show (image17);
  gtk_container_add (GTK_CONTAINER (vdr_eventbox2), image17);
  gtk_widget_set_size_request (image17, 75, 35);

  update = gtk_button_new ();
  gtk_widget_show (update);
  gtk_fixed_put (GTK_FIXED (fixed1), update, 176, 0);
  gtk_widget_set_size_request (update, 128, 32);
  gtk_container_set_border_width (GTK_CONTAINER (update), 1);
  gtk_tooltips_set_tip (tooltips, update, _("Update your VDR"), NULL);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (update), alignment15);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox11);

  image13 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox11), image13, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("Update"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox11), label32, FALSE, FALSE, 0);

  Exit = gtk_button_new ();
  gtk_widget_show (Exit);
  gtk_fixed_put (GTK_FIXED (fixed1), Exit, 408, 384);
  gtk_widget_set_size_request (Exit, 74, 30);
  gtk_widget_add_accelerator (Exit, "clicked", accel_group,
                              GDK_Q, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (Exit, "clicked", accel_group,
                              GDK_q, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (Exit, "clicked", accel_group,
                              GDK_Escape, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (Exit), alignment18);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox13);

  image15 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox13), image15, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("Exit"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox13), label35, FALSE, FALSE, 0);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_fixed_put (GTK_FIXED (fixed1), frame1, 0, 48);
  gtk_widget_set_size_request (frame1, 189, 160);
  gtk_frame_set_shadow_type (GTK_FRAME (frame1), GTK_SHADOW_IN);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (frame1), alignment1);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment1), 0, 0, 12, 0);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (alignment1), fixed4);

  vdr_sxfe = gtk_button_new ();
  gtk_widget_show (vdr_sxfe);
  gtk_fixed_put (GTK_FIXED (fixed4), vdr_sxfe, 0, 8);
  gtk_widget_set_size_request (vdr_sxfe, 160, 32);
  gtk_container_set_border_width (GTK_CONTAINER (vdr_sxfe), 1);
  gtk_tooltips_set_tip (tooltips, vdr_sxfe, _("TV-Picture with xineliboutput Frontend"), NULL);
  gtk_widget_add_accelerator (vdr_sxfe, "clicked", accel_group,
                              GDK_Return, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (vdr_sxfe, "clicked", accel_group,
                              GDK_KP_Enter, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (vdr_sxfe), alignment13);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox9);

  image10 = gtk_image_new_from_stock ("gtk-network", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox9), image10, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("vdr-sxfe (Picture)"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox9), label30, FALSE, FALSE, 0);

  vdr_sxfe_disable_autostart = gtk_button_new_with_mnemonic (_("disable Autostart"));
  gtk_widget_show (vdr_sxfe_disable_autostart);
  gtk_fixed_put (GTK_FIXED (fixed4), vdr_sxfe_disable_autostart, 0, 88);
  gtk_widget_set_size_request (vdr_sxfe_disable_autostart, 160, 24);
  gtk_container_set_border_width (GTK_CONTAINER (vdr_sxfe_disable_autostart), 1);
  gtk_tooltips_set_tip (tooltips, vdr_sxfe_disable_autostart, _("disable vdr-sxfe at systemstart"), NULL);

  vdr_sxfe_autostart = gtk_button_new_with_mnemonic (_("vdr-sxfe Autostart"));
  gtk_widget_show (vdr_sxfe_autostart);
  gtk_fixed_put (GTK_FIXED (fixed4), vdr_sxfe_autostart, 0, 56);
  gtk_widget_set_size_request (vdr_sxfe_autostart, 160, 24);
  gtk_container_set_border_width (GTK_CONTAINER (vdr_sxfe_autostart), 1);
  gtk_tooltips_set_tip (tooltips, vdr_sxfe_autostart, _("run vdr-sxfe at systemstart (only for KDE)"), NULL);

  label8 = gtk_label_new (_("<b>TV</b>"));
  gtk_widget_show (label8);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label8);
  gtk_label_set_use_markup (GTK_LABEL (label8), TRUE);
  gtk_label_set_width_chars (GTK_LABEL (label8), 0);

  frame4 = gtk_frame_new (NULL);
  gtk_widget_show (frame4);
  gtk_fixed_put (GTK_FIXED (fixed1), frame4, 208, 48);
  gtk_widget_set_size_request (frame4, 189, 160);
  gtk_frame_set_shadow_type (GTK_FRAME (frame4), GTK_SHADOW_IN);

  alignment5 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (frame4), alignment5);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment5), 0, 0, 12, 0);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (alignment5), fixed7);

  IPEntry = gtk_entry_new ();
  gtk_widget_show (IPEntry);
  gtk_fixed_put (GTK_FIXED (fixed7), IPEntry, 24, 8);
  gtk_widget_set_size_request (IPEntry, 136, 24);
  gtk_tooltips_set_tip (tooltips, IPEntry, _("Network IP-Adress from VDR Server, with xineliboutput is only one client possible. For more clients you must use streamdev-plugin. Do this on Client"), NULL);
  gtk_entry_set_text (GTK_ENTRY (IPEntry), _("localhost"));

  label39 = gtk_label_new (_("IP:"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed7), label39, 0, 8);
  gtk_widget_set_size_request (label39, 23, 24);

  allowclient = gtk_button_new_with_mnemonic (_("Allow client access"));
  gtk_widget_show (allowclient);
  gtk_fixed_put (GTK_FIXED (fixed7), allowclient, 0, 40);
  gtk_widget_set_size_request (allowclient, 160, 24);
  gtk_tooltips_set_tip (tooltips, allowclient, _("Allow client connect (insert IP from client). Do this on Server"), NULL);

  network_transport_tcp = gtk_button_new_with_mnemonic (_("TCP network transport"));
  gtk_widget_show (network_transport_tcp);
  gtk_fixed_put (GTK_FIXED (fixed7), network_transport_tcp, 0, 80);
  gtk_widget_set_size_request (network_transport_tcp, 160, 24);
  gtk_tooltips_set_tip (tooltips, network_transport_tcp, _("TCP network transport. Use this on server or client (default)"), NULL);

  udp_network_transport = gtk_button_new_with_mnemonic (_("UDP network transport"));
  gtk_widget_show (udp_network_transport);
  gtk_fixed_put (GTK_FIXED (fixed7), udp_network_transport, 0, 112);
  gtk_widget_set_size_request (udp_network_transport, 160, 24);
  gtk_tooltips_set_tip (tooltips, udp_network_transport, _("UDP network transport. Use this on server or client"), NULL);

  label22 = gtk_label_new (_("<b>Streaming</b>"));
  gtk_widget_show (label22);
  gtk_frame_set_label_widget (GTK_FRAME (frame4), label22);
  gtk_label_set_use_markup (GTK_LABEL (label22), TRUE);
  gtk_label_set_width_chars (GTK_LABEL (label22), 0);

  frame5 = gtk_frame_new (NULL);
  gtk_widget_show (frame5);
  gtk_fixed_put (GTK_FIXED (fixed1), frame5, 256, 216);
  gtk_widget_set_size_request (frame5, 140, 200);
  gtk_frame_set_shadow_type (GTK_FRAME (frame5), GTK_SHADOW_IN);

  alignment16 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (frame5), alignment16);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment16), 0, 0, 12, 0);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (alignment16), fixed8);

  fullscreenoff = gtk_button_new_with_mnemonic (_("TV Fullscreen off"));
  gtk_widget_show (fullscreenoff);
  gtk_fixed_put (GTK_FIXED (fixed8), fullscreenoff, 0, 152);
  gtk_widget_set_size_request (fullscreenoff, 112, 24);
  gtk_tooltips_set_tip (tooltips, fullscreenoff, _("Start TV-Picture in normal mode"), NULL);

  vdradmin = gtk_button_new ();
  gtk_widget_show (vdradmin);
  gtk_fixed_put (GTK_FIXED (fixed8), vdradmin, 0, 8);
  gtk_widget_set_size_request (vdradmin, 112, 32);
  gtk_tooltips_set_tip (tooltips, vdradmin, _("Web-Frontend (vdradmin)"), NULL);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (vdradmin), alignment19);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox14);

  image16 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox14), image16, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("Web-Frontend"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox14), label36, FALSE, FALSE, 0);

  user_manual = gtk_button_new_with_mnemonic (_("User Manual"));
  gtk_widget_show (user_manual);
  gtk_fixed_put (GTK_FIXED (fixed8), user_manual, 0, 48);
  gtk_widget_set_size_request (user_manual, 112, 24);
  gtk_tooltips_set_tip (tooltips, user_manual, _("VDR User Manual"), NULL);

  fullscreen = gtk_button_new_with_mnemonic (_("TV Fullscreen"));
  gtk_widget_show (fullscreen);
  gtk_fixed_put (GTK_FIXED (fixed8), fullscreen, 0, 120);
  gtk_widget_set_size_request (fullscreen, 112, 24);
  gtk_tooltips_set_tip (tooltips, fullscreen, _("Start TV-Picture in Fullscreen mode"), NULL);

  label33 = gtk_label_new (_("<b>Others</b>"));
  gtk_widget_show (label33);
  gtk_frame_set_label_widget (GTK_FRAME (frame5), label33);
  gtk_label_set_use_markup (GTK_LABEL (label33), TRUE);
  gtk_label_set_width_chars (GTK_LABEL (label33), 0);

  label37 = gtk_label_new (_("by\nHorst  J. Tritremmel (hjt)"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed1), label37, 416, 56);
  gtk_widget_set_size_request (label37, 45, 157);
  gtk_label_set_angle (GTK_LABEL (label37), 270);

  label1 = gtk_label_new (_("Action"));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label1);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed9);

  textview1 = gtk_text_view_new ();
  gtk_widget_show (textview1);
  gtk_fixed_put (GTK_FIXED (fixed9), textview1, 16, 8);
  gtk_widget_set_size_request (textview1, 152, 416);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview1)), _("Up\t\t\tUp\nDown\t\tDown\nMenu\t\tm\nOk\t\t\tReturn\nBack\t\tBackSpace\nLeft\t\t\tLeft\nRight\t\tRight\nRed\t\t\tF1\nGreen\t\tF2\nYellow\t\tF3\nBlue\t\tF4\n0\t\t\t0\n1\t\t\t1\n2\t\t\t2\n3\t\t\t3\n4\t\t\t4\n5\t\t\t5\n6\t\t\t6\n7\t\t\t7\n8\t\t\t8\n9\t\t\t9\nInfo\t\t\ti\nPause\t\tspace\nFastFwd\t\tF6\nFastRew\t\tF5\nPower\t\tp\nVolume+\tF12\nVolume-\t\tF11\nMute    \t\tF10"), -1);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed9), button1, 408, 392);
  gtk_widget_set_size_request (button1, 74, 30);
  gtk_widget_add_accelerator (button1, "clicked", accel_group,
                              GDK_Q, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (button1, "clicked", accel_group,
                              GDK_q, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (button1, "clicked", accel_group,
                              GDK_Escape, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button1), alignment20);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox15);

  image18 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox15), image18, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("Exit"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox15), label38, FALSE, FALSE, 0);

  label3 = gtk_label_new (_("Keyboardlayout"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label3);

  g_signal_connect ((gpointer) window1, "delete_event",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) window1, "configure_event",
                    G_CALLBACK (on_window1_configure_event),
                    NULL);
  g_signal_connect ((gpointer) vdr_start, "clicked",
                    G_CALLBACK (on_vdr_start_clicked),
                    NULL);
  g_signal_connect ((gpointer) vdr_stop, "clicked",
                    G_CALLBACK (on_vdr_stop_clicked),
                    NULL);
  g_signal_connect ((gpointer) wpvrscan, "clicked",
                    G_CALLBACK (on_wpvrscan_clicked),
                    NULL);
  g_signal_connect ((gpointer) videodir, "clicked",
                    G_CALLBACK (on_videodir_clicked),
                    NULL);
  g_signal_connect ((gpointer) language_automatic, "clicked",
                    G_CALLBACK (on_language_automatic_clicked),
                    NULL);
  g_signal_connect ((gpointer) language_manuel, "clicked",
                    G_CALLBACK (on_language_manuel_clicked),
                    NULL);
  g_signal_connect ((gpointer) vdr_autostart, "clicked",
                    G_CALLBACK (on_vdr_autostart_clicked),
                    NULL);
  g_signal_connect ((gpointer) vdr_disable_autostart, "clicked",
                    G_CALLBACK (on_vdr_disable_autostart_clicked),
                    NULL);
  g_signal_connect ((gpointer) channelslist, "clicked",
                    G_CALLBACK (on_channelslist_clicked),
                    NULL);
  g_signal_connect ((gpointer) sidux_eventbox1, "button_press_event",
                    G_CALLBACK (on_sidux_eventbox1_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) vdr_eventbox2, "button_press_event",
                    G_CALLBACK (on_vdr_eventbox2_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) update, "clicked",
                    G_CALLBACK (on_update_clicked),
                    NULL);
  g_signal_connect ((gpointer) Exit, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) vdr_sxfe, "clicked",
                    G_CALLBACK (on_vdr_sxfe_clicked),
                    NULL);
  g_signal_connect ((gpointer) vdr_sxfe, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) vdr_sxfe_disable_autostart, "clicked",
                    G_CALLBACK (on_vdr_sxfe_disable_autostart_clicked),
                    NULL);
  g_signal_connect ((gpointer) vdr_sxfe_autostart, "clicked",
                    G_CALLBACK (on_vdr_sxfe_autostart_clicked),
                    NULL);
  g_signal_connect ((gpointer) IPEntry, "activate",
                    G_CALLBACK (on_IPEntry_activate),
                    NULL);
  g_signal_connect ((gpointer) allowclient, "clicked",
                    G_CALLBACK (on_allowclient_clicked),
                    NULL);
  g_signal_connect ((gpointer) network_transport_tcp, "clicked",
                    G_CALLBACK (on_network_transport_tcp_clicked),
                    NULL);
  g_signal_connect ((gpointer) udp_network_transport, "clicked",
                    G_CALLBACK (on_udp_network_transport_clicked),
                    NULL);
  g_signal_connect ((gpointer) fullscreenoff, "clicked",
                    G_CALLBACK (on_fullscreenoff_clicked),
                    NULL);
  g_signal_connect ((gpointer) vdradmin, "clicked",
                    G_CALLBACK (on_vdradmin_clicked),
                    NULL);
  g_signal_connect ((gpointer) user_manual, "clicked",
                    G_CALLBACK (on_user_manual_clicked),
                    NULL);
  g_signal_connect ((gpointer) fullscreen, "clicked",
                    G_CALLBACK (on_fullscreen_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (window1, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window1, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window1, vdr_start, "vdr_start");
  GLADE_HOOKUP_OBJECT (window1, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window1, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window1, image7, "image7");
  GLADE_HOOKUP_OBJECT (window1, label27, "label27");
  GLADE_HOOKUP_OBJECT (window1, vdr_stop, "vdr_stop");
  GLADE_HOOKUP_OBJECT (window1, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window1, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window1, image9, "image9");
  GLADE_HOOKUP_OBJECT (window1, label29, "label29");
  GLADE_HOOKUP_OBJECT (window1, wpvrscan, "wpvrscan");
  GLADE_HOOKUP_OBJECT (window1, videodir, "videodir");
  GLADE_HOOKUP_OBJECT (window1, language_automatic, "language_automatic");
  GLADE_HOOKUP_OBJECT (window1, language_manuel, "language_manuel");
  GLADE_HOOKUP_OBJECT (window1, vdr_autostart, "vdr_autostart");
  GLADE_HOOKUP_OBJECT (window1, vdr_disable_autostart, "vdr_disable_autostart");
  GLADE_HOOKUP_OBJECT (window1, channelslist, "channelslist");
  GLADE_HOOKUP_OBJECT (window1, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (window1, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window1, image14, "image14");
  GLADE_HOOKUP_OBJECT (window1, label34, "label34");
  GLADE_HOOKUP_OBJECT (window1, label13, "label13");
  GLADE_HOOKUP_OBJECT (window1, sidux_eventbox1, "sidux_eventbox1");
  GLADE_HOOKUP_OBJECT (window1, image12, "image12");
  GLADE_HOOKUP_OBJECT (window1, vdr_eventbox2, "vdr_eventbox2");
  GLADE_HOOKUP_OBJECT (window1, image17, "image17");
  GLADE_HOOKUP_OBJECT (window1, update, "update");
  GLADE_HOOKUP_OBJECT (window1, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (window1, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window1, image13, "image13");
  GLADE_HOOKUP_OBJECT (window1, label32, "label32");
  GLADE_HOOKUP_OBJECT (window1, Exit, "Exit");
  GLADE_HOOKUP_OBJECT (window1, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (window1, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window1, image15, "image15");
  GLADE_HOOKUP_OBJECT (window1, label35, "label35");
  GLADE_HOOKUP_OBJECT (window1, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (window1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window1, vdr_sxfe, "vdr_sxfe");
  GLADE_HOOKUP_OBJECT (window1, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window1, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window1, image10, "image10");
  GLADE_HOOKUP_OBJECT (window1, label30, "label30");
  GLADE_HOOKUP_OBJECT (window1, vdr_sxfe_disable_autostart, "vdr_sxfe_disable_autostart");
  GLADE_HOOKUP_OBJECT (window1, vdr_sxfe_autostart, "vdr_sxfe_autostart");
  GLADE_HOOKUP_OBJECT (window1, label8, "label8");
  GLADE_HOOKUP_OBJECT (window1, frame4, "frame4");
  GLADE_HOOKUP_OBJECT (window1, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window1, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window1, IPEntry, "IPEntry");
  GLADE_HOOKUP_OBJECT (window1, label39, "label39");
  GLADE_HOOKUP_OBJECT (window1, allowclient, "allowclient");
  GLADE_HOOKUP_OBJECT (window1, network_transport_tcp, "network_transport_tcp");
  GLADE_HOOKUP_OBJECT (window1, udp_network_transport, "udp_network_transport");
  GLADE_HOOKUP_OBJECT (window1, label22, "label22");
  GLADE_HOOKUP_OBJECT (window1, frame5, "frame5");
  GLADE_HOOKUP_OBJECT (window1, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window1, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (window1, fullscreenoff, "fullscreenoff");
  GLADE_HOOKUP_OBJECT (window1, vdradmin, "vdradmin");
  GLADE_HOOKUP_OBJECT (window1, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (window1, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window1, image16, "image16");
  GLADE_HOOKUP_OBJECT (window1, label36, "label36");
  GLADE_HOOKUP_OBJECT (window1, user_manual, "user_manual");
  GLADE_HOOKUP_OBJECT (window1, fullscreen, "fullscreen");
  GLADE_HOOKUP_OBJECT (window1, label33, "label33");
  GLADE_HOOKUP_OBJECT (window1, label37, "label37");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (window1, textview1, "textview1");
  GLADE_HOOKUP_OBJECT (window1, button1, "button1");
  GLADE_HOOKUP_OBJECT (window1, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (window1, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window1, image18, "image18");
  GLADE_HOOKUP_OBJECT (window1, label38, "label38");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");
  GLADE_HOOKUP_OBJECT_NO_REF (window1, tooltips, "tooltips");

  gtk_widget_grab_focus (vdr_sxfe);
  gtk_window_add_accel_group (GTK_WINDOW (window1), accel_group);

  return window1;
}

